[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "packforge"
version = "0.1.0a1"
description = "Open-source framework for Creative Assembly Total War modding."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"

authors = [
    { name = "alventain", email = "alainalventain@gmail.com" }
]

keywords = [
    "total-war",
    "creative-assembly",
    "modding",
    "pack",
    "framework",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
